[phases.build]
cmds = []

[phases.install]
cmds = ["npm ci --omit=dev --omit=optional"]

[start]
cmd = "node src/backend/server.mjs"

[deploy]
healthcheckPath = "/api/tokens/top"
healthcheckTimeout = 300
numReplicas = 1
